version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      # タグが prod- で始まるか確認
      - TAG2=$(git describe --tags --exact-match $CODEBUILD_SOURCE_VERSION 2>/dev/null || true)
      - TAG=$(git describe --tags)
      - echo "DEBUG: Extracted TAG=$TAG"
      - echo "DEBUG: Extracted TAG=$TAG2"
      - |
        if [[ -z "$TAG" || ! "$TAG" =~ ^prod- ]]; then
          echo "Deploy skipped: Tag '$TAG' does not start with 'prod-'";
          exit 1;
        fi
      - echo "PROD DEPLOY: Valid tag detected ($TAG)"
      - echo "Navigating to the backend directory..."
      - cd uag-backend
      - echo "Installing dependencies..."
      - ./gradlew clean
  build:
    commands:
      - echo "Building the backend..."
      - ./gradlew build -x test
  post_build:
    commands:
      - echo "Build completed, preparing artifacts..."
      - mkdir -p ../build-output
      - cp build/libs/*.war ../build-output/
      - cp ../aws/codedeploy/appspec.yml ../build-output/
      - cp -r ../aws/codedeploy/scripts/*.sh ../build-output/

artifacts:
  files:
    - build-output/**

cache:
  paths:
    - /root/.gradle/caches/**