version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Navigating to the backend directory..."
      - cd asb/asb-backend
      - echo "Installing dependencies..."
      - ./gradlew clean
  build:
    commands:
      - echo "Building the backend..."
      - ./gradlew build -x test
  # post_build:
  #   commands:
  #     - echo "Build completed, preparing artifacts..."
  #     - mkdir -p ../../build-output
  #     - cp build/libs/*.war ../../build-output/
  #     - cp ../../codedeploy/appspec.yml ../../build-output/
  #     - cp -r ../../codedeploy/scripts/*.sh ../../build-output/
  post_build:
    commands:
      - echo "Build completed, preparing artifacts..."
      
      # デバッグ: build/libs/ の中身を確認
      - echo "Checking build/libs/ contents..."
      - ls -la build/libs/
      
      # デバッグ: ../../codedeploy/ の中身を確認
      - echo "Checking ../../codedeploy/ contents..."
      - ls -la ../../codedeploy/
      - echo "Checking ../../codedeploy/scripts/ contents..."
      - ls -la ../../codedeploy/scripts/
      
      # ディレクトリ作成
      - mkdir -p ../../build-output
      
      # WAR ファイルをコピー（存在する場合のみ）
      - if [ -f build/libs/*.war ]; then
          cp build/libs/*.war ../../build-output/;
          echo "WAR file copied successfully.";
        else
          echo "Error: No WAR file found in build/libs/";
        fi
      
      # appspec.yml をコピー（存在する場合のみ）
      - if [ -f ../../codedeploy/appspec.yml ]; then
          cp ../../codedeploy/appspec.yml ../../build-output/;
          echo "appspec.yml copied successfully.";
        else
          echo "Error: appspec.yml not found in ../../codedeploy/";
        fi
      
      # scripts/*.sh をコピー（存在する場合のみ）
      - if ls ../../codedeploy/scripts/*.sh 1> /dev/null 2>&1; then
          cp -r ../../codedeploy/scripts/*.sh ../../build-output/;
          echo "Scripts copied successfully.";
        else
          echo "Error: No .sh files found in ../../codedeploy/scripts/";
        fi

artifacts:
  files:
    - ../../build-output/**

cache:
  paths:
    - /root/.gradle/caches/**