logging:
  level:
    root: INFO
    org.springframework.web: INFO

cors:
  origins: https://uag-test-staging.click,https://main.dikxsy3mbqtz7.amplifyapp.com

aws:
  secrets:
    region: us-east-1
    user-token-secret: asb/dev/userTokenSecret
    user-token-secret-key: userTokenSecret
    admin-user-id-key: adminUserId
    s3: asb/dev/s3
    s3-region-key: region
    s3-bucket-key: bucket
    dynamodb: asb/dev/dynamodb
    dynamodb-region-key: region
    dynamodb-url-key: url
  cognito:
    region: us-east-1
    pool-id: us-east-1_87sFPpVTk
  cdn:
    active: false
    url: https://dev.deadbeaf1234.net